# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Jobs.proto for package 'protos'

require 'grpc'
require_relative 'Jobs_pb'

module Protos
  module Jobs
    # 定义一个服务
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protos.Jobs'

      # 定义这个服务的rpc方法
      # 生成的接口代码作为客户端与服务端的约定，服务端必须实现定义的所有接口方法，客户端直接调用同名方法向服务端发起请求。
      rpc :GetJob, ::Protos::GetJobReq, ::Protos::GetJobResp
    end

    Stub = Service.rpc_stub_class
  end
end
