# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Jobs.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Jobs.proto", :syntax => :proto3) do
    add_message "protos.GetJobReq" do
      optional :ip, :string, 20
      optional :name, :string, 50
    end
    add_message "protos.GetJobResp" do
      optional :ip, :string, 20
      optional :name, :string, 50
      optional :flag, :uint64, 1
    end
  end
end

module Protos
  GetJobReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.GetJobReq").msgclass
  GetJobResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.GetJobResp").msgclass
end
